### ISSUE TITLE
graceful shutdowns

### ISSUE THREAD

**Issue by biw** [heroku/heroku-buildpack-nginx#31]
Hello 👋, I'm having a little trouble making sure that my server restarts gracefully. I have my script waiting for `SIGTERM` but it doesn't seem like they get called, is there a way I can watch for them and pass them to my (node) app? 😄

**Comment by garhiggins** [comment]
I've been struggling with this also. We forked the start script and trapped the `SIGTERM` and then send the `nginx -s QUIT`, but it doesn't seem to help. I believe the problem is that Heroku sends a `SIGTERM` to all processes (https://devcenter.heroku.com/articles/dynos#shutdown), not just the bash script, so nginx still sees a `SIGTERM` and does a fast shutdown. We drop a ton of requests every time we deploy :(

**Comment by sidonath** [comment]
Ouch!

I looked into the source and there's a [`TODO: #ifndef`](https://github.com/nginx/nginx/blame/4bf4650f2f10f7bbacfe7a33da744f18951d416d/src/core/ngx_config.h#L59) next to

```
#define NGX_SHUTDOWN_SIGNAL      QUIT
#define NGX_TERMINATE_SIGNAL     TERM
```

If we could land a change in Nginx to wrap those two within `#ifndef` indeed, we could compile a Heroku-friendlier version of Nginx that treats `SIGTERM` as `SIGQUIT`. Not sure if that's a _good_ idea, but it would help with this issue.

**Comment by mguida22** [comment]
:eyes: Any updates on this?

**Comment by beanieboi** [comment]
@mguida22 this is outside of the scope of this buildpack. it has to do with the Heroku platform itself and how nginx works. there is nothing this buildpack can do.

**Comment by mguida22** [comment]
@beanieboi thanks for the reply!

Is there a better place to bring up this issue with the Heroku platform?

**Comment by beanieboi** [comment]
@mguida22 This is a known issue and since this i a behavior of the platform for a long time, i believe there is no way to fix it without breaking a lot of applications. I think our only chance is to patch nginx to react differently. We do this in the pgbouncer buildpack and it works ok.
https://github.com/heroku/heroku-buildpack-pgbouncer/blob/master/support/patchfiles/1.13.0/0001-Disable-SIGTERM.patch
